rmac ndos $$pz sz
link ndos[os]
rmac nios $$pz sz
link nios[os]
rmac niosaltr $$pz sz
link niosaltr[os]
rmac nios-kp2 $$pz sz
link nios-kp2[os]
rmac nios-t80 $$pz sz
link nios-t80[os]
era *.rel
era *.sym
mac ldndos $$pz sz
load ldndos
mac cd $$pz sz
load cd
mac mkdir $$pz sz
load mkdir
mac rmdir $$pz sz
load rmdir
mac necho $$pz sz
load necho
mac nstat $$pz sz
load nstat
mac nsh $$pz sz
load nsh
era *.hex
